"""empty message

Revision ID: 2deb23ae5d01
Revises: c60eaa2dfb8a
Create Date: 2022-11-02 20:17:57.000935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2deb23ae5d01'
down_revision = 'c60eaa2dfb8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'nome')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('nome', sa.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
