"""empty message

Revision ID: 98a611d1cd04
Revises: 136bc4841a85
Create Date: 2022-11-02 18:53:05.104846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a611d1cd04'
down_revision = '136bc4841a85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('nome', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'nome')
    # ### end Alembic commands ###
